import { Row, Col, Typography } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Row
                    style={{
                        minHeight: '100vh',
                        backgroundColor: 'whitesmoke',
                    }}
                >
                    <Col
                        span={24}
                        style={{
                            display: 'flex',
                            justifyContent: 'center',
                            alignItems: 'center',
                        }}
                    >
                        <Typography.Title>Hello World!</Typography.Title>
                    </Col>
                </Row>
            </main>
        </div>
    )
}

export default Home
